version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_suite
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crm_suite?schema=public
      JWT_SECRET: change_this_secret
      APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  db_data: