version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app
      SECRET_KEY: please-change-in-prod
      UVICORN_WORKERS: 2
      ENABLE_DOCS: "true"
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: