[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "PL"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
  "tests/*",
]